from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 892)
        MainWindow.setStyleSheet("img:url(:/newPrefix/image/Quat.png)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 350, 81, 31))
        self.pushButton.setStyleSheet("COLOR:rgb(0, 0, 0);background-color: rgb(0, 85, 255);\n"
"font: 75 italic 12pt \"Arial\";\n"
"font: 75 12pt \"Arial\";\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 220, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 0, 211, 121))
        self.label_2.setStyleSheet("image:url(:/newPrefix/image/logo.jpg)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 561, 111))
        self.label_3.setStyleSheet("image:url(:/newPrefix/image/Vien.png)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 120, 701, 61))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 180, 171, 151))
        self.label_5.setStyleSheet("IMAGE:url(:/newPrefix/image/Quat.png)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 350, 81, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 75 italic 12pt \"Arial\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 180, 211, 161))
        self.label_6.setStyleSheet("image:url(:/newPrefix/image/tivi.png)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 170, 171, 161))
        self.label_7.setStyleSheet("image:url(:/newPrefix/image/bongden.png)")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(530, 380, 261, 161))
        self.comboBox.setObjectName("comboBox")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(540, 380, 141, 41))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(540, 440, 141, 41))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(540, 500, 141, 41))
        self.label_10.setObjectName("label_10")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(0, 440, 321, 101))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 450, 281, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 490, 281, 31))
        self.label_12.setObjectName("label_12")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 340, 81, 31))
        self.pushButton_3.setStyleSheet("COLOR:rgb(0, 0, 0);background-color: rgb(0, 85, 255);\n"
"font: 75 italic 12pt \"Arial\";\n"
"font: 75 12pt \"Arial\";\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 340, 81, 31))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 75 italic 12pt \"Arial\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(660, 340, 81, 31))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 75 italic 12pt \"Arial\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(560, 340, 81, 31))
        self.pushButton_6.setStyleSheet("COLOR:rgb(0, 0, 0);background-color: rgb(0, 85, 255);\n"
"font: 75 italic 12pt \"Arial\";\n"
"font: 75 12pt \"Arial\";\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.widget_bieudo = QtWidgets.QWidget(self.centralwidget)
        self.widget_bieudo.setGeometry(QtCore.QRect(110, 550, 581, 281))
        self.widget_bieudo.setObjectName("widget_bieudo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "ON"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">ĐIỀU KHIỂN VÀ GIÁM SÁT MÔI TRƯỜNG </span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "OFF"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">NHIỆT ĐỘ:</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">ĐỘ ẨM</span><span style=\" font-size:12pt; font-weight:600;\">:</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">ÁNH SÁNG:</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">HỌ VÀ TÊN:</span><span style=\" font-size:12pt;\"> Trần Ngọc Linh</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">MSSV:</span><span style=\" font-size:12pt;\"> 23161289</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "ON"))
        self.pushButton_4.setText(_translate("MainWindow", "OFF"))
        self.pushButton_5.setText(_translate("MainWindow", "OFF"))
        self.pushButton_6.setText(_translate("MainWindow", "ON"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
